### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by ExistsAndIs1** [turboladen/playful#1]
Hi 

Is this project still active?
gem install upnp => not found in any repository
- page on rubygems is 404
  http://rubygems.org/gems/upnp

thx
Stefan

**Comment by turboladen** [comment]
I've been slowly plugging away at this for quite some time, but still haven't gotten it to a releasable point yet (hence, the 404 on rubygems.org).  I should really remove that URL.  I'm still hoping to get this off the ground at some point, but don't yet have any timeframe for it.
