### ISSUE TITLE
git://github.com/turboladen/upnp.git (at master) is not checked out. Please run `bundle install` (Bundler::GitError) on Passenger

### ISSUE THREAD

**Issue by kenan-memis** [turboladen/playful#8]
Hi,

I have to try my application in production mode, such as on a vps setup. So I installed nginx with passenger on my localhost..I made all necessary configurations. nginx works perfect..

But I am getting this error..

git://github.com/turboladen/upnp.git (at master) is not checked out. Please run `bundle install` (Bundler::GitError)
  /home/kenani/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler/source/git.rb:176:in `rescue in load_spec_files'

So, in my Gemfile I have this:

gem 'upnp', :git => 'git://github.com/turboladen/upnp.git'

As rails version I use Rails 3.2.8, and Ruby 1.9.3.. I deleted Gemfile.lock file and re run bundle install too many times but the same issue..

I am stacked. What could be possible reason for this problem.

Thanks.

**Comment by kenan-memis** [comment]
Sorry, 

I have forgotten to run 

bundle install --deployment

so it is working now..

**Comment by turboladen** [comment]
Glad you figured it out.
